# Generated by Django 4.2.23 on 2025-07-10 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satisfaction', models.CharField(choices=[('good', '만족해요'), ('soso', '보통이에요'), ('bad', '별로예요')], max_length=10)),
                ('size_feel', models.CharField(choices=[('big', '크게 느껴져요'), ('normal', '적당해요'), ('small', '작게 느껴져요')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
