# Generated by Django 4.2.23 on 2025-07-06 14:57

from django.db import migrations
import os

def create_social_apps(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    site, _ = Site.objects.get_or_create(domain='127.0.0.1:8000', defaults={'name': 'localhost'})

    #카카오
    kakao_app, created = SocialApp.objects.get_or_create(
        provider='kakao',
        defaults={
            'name': 'Kakao',
            'client_id': os.getenv('KAKAO_CLIENT_ID'),
            'secret':  os.getenv('KAKAO_SECRET'),
        },
    )
    if created:
        kakao_app.sites.add(site)

    #구글
    google_app, created = SocialApp.objects.get_or_create(
        provider='google',
        defaults={
            'name': 'Google',
            'client_id': os.getenv('GOOGLE_CLIENT_ID'),
            'secret': os.getenv('GOOGLE_SECRET'),
        },
    )
    if created:
        google_app.sites.add(site)

class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_social_apps),
    ]
