# Generated by Django 4.2.23 on 2025-07-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userprofile_hip_userprofile_waist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cup_size',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
